/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/audius/': RouteRecordInfo<'/audius/', '/audius', Record<never, never>, Record<never, never>>,
    '/audius/playlists/[id]': RouteRecordInfo<'/audius/playlists/[id]', '/audius/playlists/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/audius/users/[id]': RouteRecordInfo<'/audius/users/[id]', '/audius/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/designs': RouteRecordInfo<'/designs', '/designs', Record<never, never>, Record<never, never>>,
    '/donate': RouteRecordInfo<'/donate', '/donate', Record<never, never>, Record<never, never>>,
    '/editor/': RouteRecordInfo<'/editor/', '/editor', Record<never, never>, Record<never, never>>,
    '/premium': RouteRecordInfo<'/premium', '/premium', Record<never, never>, Record<never, never>>,
    '/roadmap': RouteRecordInfo<'/roadmap', '/roadmap', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/studies/': RouteRecordInfo<'/studies/', '/studies', Record<never, never>, Record<never, never>>,
    '/studies/[id]': RouteRecordInfo<'/studies/[id]', '/studies/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/visualizer': RouteRecordInfo<'/visualizer', '/visualizer', Record<never, never>, Record<never, never>>,
  }
}
