export type AUDIO_SOURCE = 'SPOTIFY' | 'AUDIUS' | 'MICROPHONE' | 'RADIO_PARADISE' | 'KEXP' | 'FILE' | 'S3' | 'LINK'

const SPOTIFY: AUDIO_SOURCE = 'SPOTIFY';
const AUDIUS: AUDIO_SOURCE = 'AUDIUS';
const MICROPHONE: AUDIO_SOURCE = 'MICROPHONE';
const RADIO_PARADISE: AUDIO_SOURCE = 'RADIO_PARADISE';
const KEXP: AUDIO_SOURCE = 'KEXP';
const FILE: AUDIO_SOURCE = 'FILE';
const S3: AUDIO_SOURCE = 'S3';
const LINK: AUDIO_SOURCE = 'LINK'

export const AUDIO_SOURCES ={
  SPOTIFY,
  AUDIUS,
  MICROPHONE,
  RADIO_PARADISE,
  KEXP,
  FILE,
  S3,
  LINK
};
